### ISSUE TITLE
any master can help me ?

### ISSUE THREAD

**Issue by norikohxb** [mnayef95/broadlink-s3-hub-app-daemon#6]
I only add 1 s3c +1 tc3 into the apps.yaml

---
hello_world:
  module: hello
  class: HelloWorld

YuShiTC3:
  module: broadlink_s3_hub
  class: BroadlinkS3Hub
  hub_ip: "192.168.216.11"
  did: "00000000000000000000ec0bae96ee55"
  scan_interval: 2
  friendly_names:
    - 浴室吸顶灯
    - 浴室青空灯
    - 浴室浴霸
  entity_ids:
    - light.yushitc31
    - light.yushitc32
    - light.yushitc33

only 1 devices  1 tc3 no others 
and it work i can turn 3 lights on or off
successfully! but 
why does the system log display below error it relate about RMpro
but I did not add any RM pro into they apps.yaml

2024-10-02 04:51:02.051975 WARNING YuShiTC3: ------------------------------------------------------------
2024-10-02 04:51:02.052221 WARNING YuShiTC3: Unexpected error in worker for App YuShiTC3:
2024-10-02 04:51:02.052338 WARNING YuShiTC3: Worker Ags: {'id': 'a6871b370e4f49e5a0dc1136578ac03b', 'name': 'YuShiTC3', 'objectid': '24e7f70c1eeb473287f18a0bd693d28b', 'type': 'event', 'event': 'call_service', 'function': <bound method BroadlinkS3Hub.change_state of <broadlink_s3_hub.BroadlinkS3Hub object at 0x7f1f71700190>>, 'data': {'domain': 'remote', 'service': 'send_command', 'service_data': {'num_repeats': 1, 'delay_secs': 0.4, 'hold_secs': 0, 'device': '吸顶灯', 'command': '关', 'device_id': ['ce970adf163c8444a93fc3300e2877cd']}, 'metadata': {'origin': 'LOCAL', 'time_fired': '2024-10-01T20:51:02.045890+00:00', 'context': {'id': '01J94XKGWA2XK78PQ8X38KGMYR', 'parent_id': '01J94XKGW79P94TNWQ9QA9KRX4', 'user_id': None}}}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2024-10-02 04:51:02.052530 WARNING YuShiTC3: ------------------------------------------------------------
2024-10-02 04:51:02.053242 WARNING YuShiTC3: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/apps/broadlink/broadlink_s3_hub.py", line 51, in change_state
    data_entity_id = data["service_data"]["entity_id"]

it is another Rmpro devices  a remote of broadlink 
it has no relationship with this tc3 and with the s3 hub
why it will keep on show those errors

in app daemon I  only add 1 s3 and 1 tc3-3 
I did not config the rmpro in apps.yaml.

how to make those logs disappear

Question 2  
how to add door sensor ds4-fc  (it works with s3 hub)  into the appdaemone?

**Comment by norikohxb** [comment]
and i also can get below error message in log

2024-10-02 05:39:51.228944 WARNING YuShiTC3: ------------------------------------------------------------
2024-10-02 05:39:51.229147 WARNING YuShiTC3: Unexpected error in worker for App YuShiTC3:
2024-10-02 05:39:51.229316 WARNING YuShiTC3: Worker Ags: {'id': '757fcc645a2f41f59edfdd2f4d92c9d4', 'name': 'YuShiTC3', 'objectid': 'bc5a6e5a997745d3ab2a8f4110a84645', 'type': 'event', 'event': 'call_service', 'function': <bound method BroadlinkS3Hub.change_state of <broadlink_s3_hub.BroadlinkS3Hub object at 0x7f88cd40bbd0>>, 'data': {'domain': 'system_log', 'service': 'write', 'service_data': {'logger': 'frontend.js.modern.202409091', 'message': 'Unhandled promise rejection from Chrome 129.0.0.0 on Windows 10\n{\n  "code": "not_found",\n  "message": "Subscription not found."\n}', 'level': 'debug'}, 'metadata': {'origin': 'LOCAL', 'time_fired': '2024-10-01T21:39:51.226526+00:00', 'context': {'id': '01J950CY9T44AR2KJ9VQ9PW5FV', 'parent_id': None, 'user_id': 'eb25c96f57e542d49588fa2bc53a1d1f'}}}, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2024-10-02 05:39:51.229518 WARNING YuShiTC3: ------------------------------------------------------------
2024-10-02 05:39:51.230077 WARNING YuShiTC3: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1095, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/apps/broadlink/broadlink_s3_hub.py", line 51, in change_state
    data_entity_id = data["service_data"]["entity_id"]
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^

**Comment by norikohxb** [comment]
any way to supoprt broadlink s3 hub's door sensor
